services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: go-app
    depends_on:
      - postgres
    environment:
      DB_CONNECTION_STRING: "postgresql://myuser:mypassword@postgres:5432/mydatabase?sslmode=disable"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
