services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"       # Основной порт для API и веб-интерфейса
      - "9001:9001"       # Порт для консоли управления (опционально)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data              # Локальная директория для хранения данных
      - ./config:/root/.minio     # Директория для конфигурации MinIO
    command: server /data --console-address ":9001"

  # Опционально: MinIO клиент для тестирования
  mc:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb local/mybucket || true &&
      mc ls local
      "
